import {test} from 'node:test';
import assert from 'node:assert/strict';
import {estimatePossession,estimateRoles,resolveSetup} from '../lib/possession.ts';
import {buildState,type Clip,type Track,type Frame} from '../lib/court.ts';
const player=(id:number,x:number,jersey:[number,number,number]=[.9,.85,.8]):Track=>({id,kind:'player',confidence:.9,box:[x,.3,.07,.3],vx:0,vy:0,jersey});
const ball=(x:number,y=.44):Track=>({id:99,kind:'ball',confidence:.8,box:[x,y,.012,.022],vx:0,vy:0});
const clip=(frames:Frame[]):Clip=>({duration:5,width:1280,height:720,frames,sample:false});
test('possession follows detected ball proximity, not track order or fixed player IDs',()=>{const f={time:0,tracks:[player(1,.7),player(7,.2),ball(.22)]};assert.equal(estimatePossession(clip([f]),f).handler,7);});
test('ambiguous possession and a ball in flight stay unknown',()=>{for(const tracks of [[player(1,.2),player(2,.2),ball(.22)],[player(1,.1),player(2,.8),ball(.5,.1)]]){const f={time:0,tracks};assert.equal(estimatePossession(clip([f]),f).handler,null);}});
test('possession can bridge brief ball occlusion but never use future frames or stale evidence',()=>{const frames=[{time:0,tracks:[player(7,.2),ball(.22)]},{time:.25,tracks:[player(7,.21)]},{time:1,tracks:[player(7,.23)]}];const c=clip(frames);assert.equal(estimatePossession(c,frames[1]).handler,7);assert.equal(estimatePossession(c,frames[1]).source,'recent_ball_track');assert.equal(estimatePossession(c,frames[2]).handler,null);const earlier={time:-.25,tracks:[player(7,.2)]};assert.equal(estimatePossession(c,earlier).handler,null);});
test('jersey color groups orient offense around current handler and preserve manual corrections',()=>{const f={time:0,tracks:[player(1,.1),player(2,.3),player(3,.6,[.08,.12,.2]),player(4,.8,[.1,.13,.18]),ball(.12)],basket:{x:.8,y:.2}};const c=clip([f]);const roles=estimateRoles(f,1);assert.equal(roles[2],'offense');assert.equal(roles[3],'defense');const setup=resolveSetup(c,f,{handler:null,roles:{4:'ignore'},basket:null},null);assert.equal(setup.handler,1);assert.equal(setup.roles[4],'ignore');assert.deepEqual(setup.basket,f.basket);const facts=buildState(c,f,setup)!;assert.equal(facts.handler_source,'ball_proximity');assert.equal(facts.team_source,'mixed');assert.equal(facts.spacing.visible_defense,1);assert.ok(facts.quality.limitations.some(x=>x.includes('estimated')));});
test('manual handler correction works without assigning every team',()=>{const f={time:0,tracks:[player(1,.1),player(2,.6,[.1,.1,.15])]};const c=clip([f]);const setup=resolveSetup(c,f,{handler:1,roles:{},basket:null},null);const state=buildState(c,f,setup)!;assert.equal(state.handler_source,'user_confirmed');assert.equal(state.spacing.visible_defense,1);assert.equal(state.ball_detected,false);});

test('a manual handler correction cannot silently override later possession',()=>{const f={time:1,tracks:[player(1,.1),player(2,.6),ball(.62)]};const c=clip([f]);const resolved=resolveSetup(c,f,{handler:1,roles:{1:'offense'},basket:null},null,0);assert.equal(resolved.handler,2);assert.equal(resolved.handlerSource,'ball_proximity');});

test('reopening a saved automatic decision preserves its provenance',()=>{const f={time:0,tracks:[player(1,.1),player(2,.6),ball(.12)]};const c=clip([f]);const automatic=resolveSetup(c,f,{handler:null,roles:{},basket:null},null);const restored=resolveSetup(c,f,automatic,0,0);assert.equal(restored.handlerSource,'ball_proximity');assert.equal(restored.handlerConfidence,automatic.handlerConfidence);assert.equal(restored.rolesSource,'jersey_color');});
