import type {CourtState} from './court';

export const DECISION_POLICY_VERSION='shoot-drive-v3';

// Coaching sources and their limits are documented in docs/decision-policy.md.
// These are comparative action criteria, never multipliers on JEV probabilities.
export const question={
  type:'choice',
  instructions:[
    'Which immediate action should this ball handler take NOW to create or use a good scoring opportunity? Judge the decision, not the eventual outcome. Probabilities express preference among actions, not shot-making or pass-completion rates.',
    'First check whether the handler can finish at the rim now or take a useful open shot. Otherwise compare a specific advantageous pass against a drive ONLY if the current evidence supports a one-on-one opportunity. DRIVE is not the default when a shot or pass is uncertain. Retain/reset if no advantage is supported.',
    'Do not pass up an available layup or a good open shot merely because another teammate is open. A pass must offer a concrete advantage over the handler shooting or driving: a better finish, a substantially better uncontested look, or relief from a double team/help defender.',
    'SHOOT includes layups, dunks, close finishes, floaters and jump shots. DRIVE means penetrating to create a shot that is not yet available. A moving player who can finish now should SHOOT, not keep driving. Being at the top of the key alone is not a reason to drive: a backed-off defender favors an open shot in range. Prioritize DRIVE only for a supported one-on-one opportunity: one close or closing on-ball defender, usable space beyond them, and no second defender or help able to block the proposed route. One-on-one describes the local matchup, not the total number of defenders visible on the court.',
    'Use attacking evidence, defender positions, handler movement and recent causal context. primary_defender_id is only the nearest detected defender, not a verified matchup. Check secondary defenders and unassigned players before recommending penetration. no_help_visible means no help was found in a narrow screen corridor; it does not prove a clear driving lane.',
    'If the one-on-one matchup or route is uncertain, do not rank DRIVE first. A nearest defender, a single detected defender, missing detections, or no_help_visible alone does not establish one-on-one. Visible help, a second defender in reach of the route, or congestion rules out DRIVE priority. Choose the best supported shot, specific pass or reset instead, without inventing an open shot or receiver. Current help or congestion overrides an earlier one-on-one opening.',
    'All coordinates and distances are image-plane measurements. Distances in handler heights help compare apparent spacing across zoom levels; they are not meters, feet, arm lengths or proven layup range. The hoop is elevated, so its screen position is not its floor position. Do not invent a top-of-key/paint/three-point location, shooting range, body balance, gathering motion, dribble availability, defender stance, player skill, score or shot clock.',
    'Use supportive geometry to favor a close finish or open shot when credible, but do not treat proximity alone as proof. Unknown range or a missing hoop lowers certainty; it is neither evidence that shooting is bad nor a reason to automatically prefer passing. Missing defenders do not establish an uncontested shot. Lower possession confidence weakens every action recommendation.',
    'Screen-left and screen-right are relative to the handler. Assess individual passing options; having two pass labels or many receivers must not create an automatic passing preference. Use only the current state and earlier evidence, never future frames. This is a basketball judgment experiment, not a calibrated outcome predictor.',
  ].join(' '),
  criteria:{
    SHOOT:'Take the available scoring attempt now. Strongly favor a credible immediate layup, dunk or close finish when the handler is near the rim and no effective rim contest is evident; a trailing defender is not automatically a reason to pass. Also favor an open catch-and-shoot or pull-up opportunity in plausible range when the nearest defender cannot readily contest. Shooting is not limited to stationary jump shots or to being close to the rim. Consider contest and help at the rim: closeness alone does not justify a heavily contested attempt. Do not surrender a good shot for a merely lateral pass to another open player. Use only supported readiness/range information and acknowledge what is unknown.',
    DRIVE:'Attack off the dribble to create a shot that is not yet available. Prioritize only a supported one-on-one opportunity: a close or closing on-ball defender takes away the immediate shot, there is usable space beyond that defender, and no second defender or help can block the route. One-on-one is necessary, not sufficient: an available good shot or a clearly better pass still wins. If the matchup or route is uncertain, keep DRIVE below the best supported SHOOT, PASS_LEFT, PASS_RIGHT or RESET option. Reduce DRIVE preference for visible help, multiple defenders able to contest the route, congestion, or an unassigned player who may be help. Do not reward DRIVE merely for handler movement, pressure, perimeter position or missing shooting-range information. Prefer SHOOT if the defender backs off and an open shot in range is available, or if the handler has already reached an immediate finishing opportunity. Unknown dribble status, court zone and defender stance are not observed facts.',
    PASS_LEFT:'Pass now to a visible screen-left teammate only when a plausible lane and receiver opportunity offer a concrete advantage over the handler finishing, taking an open shot, or attacking one-on-one. Examples: help commits to the handler and leaves the receiver open, a double team needs an outlet, or the receiver has a clearly better finish/look. Being open by itself is not enough to take the ball away from an available good shot. Penalize blocked/unknown lanes and absent receivers.',
    PASS_RIGHT:'Pass now to a visible screen-right teammate using the same standard as PASS_LEFT: require a plausible lane and a concrete improvement over the handler shooting or driving, such as exploiting committed help, escaping pressure or finding a clearly better finish/look. Do not prefer a routine swing pass to an available layup or good open shot. Penalize blocked/unknown lanes and absent receivers.',
    RESET:'Retain possession or reset when the available shot is poor, penetration is crowded, and no advantageous pass is supported. Do not reset simply because passing is uncertain when the handler has a credible finish, open shot or one-on-one advantage. Reflect incomplete perception with lower confidence rather than inventing an opening.',
  },
};

/** Both ingestion and replay requests receive the same policy and causal evidence. */
export function questionWithContext(state:CourtState,context:CourtState[]){
  const recent=context.filter(previous=>previous.source===state.source&&previous.ball_handler===state.ball_handler&&previous.time_seconds<state.time_seconds&&state.time_seconds-previous.time_seconds<=1)
    .sort((a,b)=>a.time_seconds-b.time_seconds).slice(-4)
    .map(previous=>({time_seconds:previous.time_seconds,ball_handler:previous.ball_handler,ball_detected:previous.ball_detected,handler_confidence:previous.handler_confidence,handler_position:previous.handler_position,movement:previous.movement,defender_distance:previous.defender_distance,basket_distance:previous.basket_distance,attacking:previous.attacking}));
  return recent.length?{...question,instructions:`${question.instructions} Earlier same-handler observations (oldest first; perspective and camera motion still apply): ${JSON.stringify(recent)}`}:question;
}
